on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.19
        ports:
          - 3307:3306
        env:
          MYSQL_USER: dev
          MYSQL_PASSWORD: ax2
          MYSQL_DATABASE: startcode_test
          MYSQL_ROOT_PASSWORD: password
    steps:
      - uses: actions/checkout@master
      - name: Build java
        run: mvn clean install
      - uses: azure/docker-login@v1
        with:
          login-server: sarson.azurecr.io
          username: ${{ secrets.acr_sarson_username }}
          password: ${{ secrets.acr_sarson_password }}

      - name: Build and push image to ACR
        id: build-image
        run: |
          docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t sarson.azurecr.io/exam:${{ github.sha }}
          docker push sarson.azurecr.io/exam:${{ github.sha }}

      - uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.aks_exam_kubeConfig }}
        id: login

      - uses: azure/k8s-create-secret@v1
        with:
          namespace: default
          container-registry-url: sarson.azurecr.io
          container-registry-username: ${{ secrets.acr_sarson_username }}
          container-registry-password: ${{ secrets.acr_sarson_password }}
          secret-name: examdockerauth

      - uses: azure/k8s-deploy@v1
        with:
          namespace: default
          manifests: |
            manifests/deployment.yml
            manifests/service.yml
            manifests/autoscaling.yml
          images: |
            sarson.azurecr.io/exam:${{ github.sha }}
          imagepullsecrets: |
            examdockerauth
