name: ci

on:
  push:
    branches: master

jobs:
  multi:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.19
        ports:
          - 3307:3306
        env:
          MYSQL_USER: dev
          MYSQL_PASSWORD: ax2
          MYSQL_DATABASE: startcode_test
          MYSQL_ROOT_PASSWORD: password
    steps:
      - uses: actions/checkout@master
      - name: Build java
        run: mvn clean install
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            user/app:latest
            user/app:1.0.0
